### ISSUE TITLE
Clarify examples in README.md

### ISSUE THREAD

**Issue by nrctkno** [cantie/app-store-connect-api-php#21]
In the provided example:

```php
$client = new AppleClient();
$client->setApiKey("PATH_TO_API_KEY");
$client->setIssuerId($issuerId);
$client->setKeyIdentifier($keyIdentifier);

$appstore = new AppleService_AppStore($client);
$results = $appstore->apps->listApps([
    "filter[bundleId]" => "YOUR_BUNDLE_ID" // filter LIKE
]);
...
```
The class names don't match with the classes available in the library. Although it's not a complex task to locate them, improving the examples would promote the adoption of the library.

**Comment by cantie** [comment]
Hi @nrctkno ,
Yes you're right. I've forgotten to note that some frequently used classes are aliased that has been declared in aliases.php.
I will update the document about aliases and add necessary includes in the examples.
